define({
    music: ['Music loop', 0],
    winTerminator: ['Congratulations', 0],
    loseTerminator: ['Better Luck Next Time - short', 0],
    costUp: ['Bet_Up', 1],
    costDown: ['Bet_Down', 1],
    costMax: ['Bet_Max', 9],
    stopButton: ['PlayButtonV2', 3],
    click: ['GenericClick_1', 2],
    wheelStart: ['discs starting to spin_v6', 2],
    wheel1: ['Discs stop spinning1_V3', 3],
    wheel2: ['Discs stop spinning2_V3', 1],
    wheel3: ['Discs stop spinning3_V3', 5],
    wheel4: ['Discs stop spinning4_V3', 7],
    pinkDiamond: ['Pink Diamond lands - Glass Chink', 3],
    wordMatch: ['WordComplete_Note', 2],
    letterMark: ['Letter highlighted - click n sparkle', 8],
    yourLetter: ['Your Letter Revealed', 4],
    bonusLetter: ['DiamondFanfare', 4],
    m3: ['PrizeAwarded - 03Words', 5],
    m4: ['PrizeAwarded - 04Words', 6],
    m5: ['PrizeAwarded - 05Words', 7],
    m6: ['PrizeAwarded - 06Words', 8],
    m7: ['PrizeAwarded - 07Words', 9],
    m8: ['PrizeAwarded - 08Words', 5],
    m9: ['PrizeAwarded - 09Words', 6],
    m10: ['PrizeAwarded - 10Words', 7],
});
